/**
 * PHOENIX MCP Launcher
 * Interactive setup and server launcher
 */

import { spawn, execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function launch() {
  console.log('');
  console.log('🔥 PHOENIX MCP Launcher');
  console.log('═'.repeat(50));
  console.log('');

  // Step 1: Check dependencies
  console.log('📦 Checking dependencies...');

  const nodeModules = path.join(__dirname, 'node_modules');
  if (!fs.existsSync(nodeModules)) {
    console.log('   Installing dependencies...');
    try {
      execSync('npm install', { cwd: __dirname, stdio: 'inherit' });
      console.log('   ✅ Dependencies installed');
    } catch (error) {
      console.log('   ❌ Failed to install dependencies');
      process.exit(1);
    }
  } else {
    console.log('   ✅ Dependencies ready');
  }

  // Step 2: Check/create .env
  console.log('');
  console.log('⚙️  Checking configuration...');

  const envPath = path.join(__dirname, '.env');
  const envTemplatePath = path.join(__dirname, '.env.template');

  if (!fs.existsSync(envPath)) {
    console.log('   No .env file found. Creating from template...');

    const frameworkPath = path.resolve(__dirname, '../..');
    const phoenixPath = path.resolve(__dirname, '..');

    const envContent = `# PHOENIX MCP Configuration
# Generated by launcher

# Server Configuration
PHOENIX_PORT=5678

# Framework Paths
FRAMEWORK_PATH=${frameworkPath}
PHOENIX_PATH=${phoenixPath}
`;

    fs.writeFileSync(envPath, envContent);
    console.log('   ✅ Configuration created');
    console.log(`   📁 Framework: ${frameworkPath}`);
  } else {
    console.log('   ✅ Configuration found');
  }

  // Step 3: Launch server
  console.log('');
  console.log('🚀 Starting PHOENIX Control Panel...');
  console.log('');

  const server = spawn('node', ['server.js'], {
    cwd: __dirname,
    stdio: 'inherit',
    env: { ...process.env }
  });

  server.on('error', (error) => {
    console.log(`❌ Failed to start server: ${error.message}`);
    process.exit(1);
  });

  server.on('close', (code) => {
    if (code !== 0) {
      console.log(`Server exited with code ${code}`);
    }
    rl.close();
  });
}

launch().catch(error => {
  console.error('Launch error:', error);
  rl.close();
  process.exit(1);
});
