<?php
/**
 * My First Dashboard2 - Generated by PHOENIX
 */

class MyFirstDashboard2_Model {

    public static function Get_Data() {
        return [
            'title' => 'My First Dashboard2',
            'config' => {},

            // Add your data here
            'items' => []
        ];
    }
}
?>
