<?php
/**
 * My First Dashboard - Generated by PHOENIX
 */

class MyFirstDashboard_Model {

    public static function Get_Data() {
        return [
            'title' => 'My First Dashboard',
            'config' => {},

            // Add your data here
            'items' => []
        ];
    }
}
?>
